name: Trigger dispatch

on:
  push:
    branches-ignore:
      - main
      - release
  pull_request:
    types: [opened, closed, synchronize]
    branches-ignore:
      - versioning
  delete:
    branches:
      - '*'
  gollum:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}

jobs:
  Print_trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger was ${{ github.event_name }}"
      
  Trigger_Dispatch:
    needs: Print_trigger
    uses: gabor-kovac/workflow/.github/workflows/dispatch.yml@main
    with:
      trigger: ${{ github.event_name }}
    secrets: inherit
